# Generated by Django 5.2.15 on 2026-06-29 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snapshots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_focus', models.CharField(choices=[('overall', 'Overall'), ('financial', 'Financial'), ('market', 'Market'), ('legal', 'Legal'), ('cultural', 'Cultural'), ('operational', 'Operational')], default='overall', max_length=32)),
                ('snapshot_a_score', models.IntegerField()),
                ('snapshot_b_score', models.IntegerField()),
                ('winner', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_a', to='snapshots.businesssnapshot')),
                ('snapshot_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_b', to='snapshots.businesssnapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot Comparison',
                'verbose_name_plural': 'Snapshot Comparisons',
                'ordering': ['-created_at'],
            },
        ),
    ]
