# Generated by Django 5.2.15 on 2026-06-29 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparisons', '0001_initial'),
        ('snapshots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('filter_focus', models.CharField(choices=[('overall', 'Overall'), ('financial', 'Financial'), ('market', 'Market'), ('legal', 'Legal'), ('cultural', 'Cultural'), ('operational', 'Operational')], default='overall', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_a', to='snapshots.businesssnapshot')),
                ('snapshot_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_b', to='snapshots.businesssnapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
                ('winner_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_comparisons', to='snapshots.businesssnapshot')),
            ],
            options={
                'verbose_name': 'Comparison',
                'verbose_name_plural': 'Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SnapshotComparison',
        ),
    ]
