# Generated by Django 5.2.15 on 2026-06-17 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='World Bank', max_length=255)),
                ('higher_is_riskier', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Economic Indicator',
                'verbose_name_plural': 'Economic Indicators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegionEconomicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='World Bank', max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_estimated', models.BooleanField(default=False)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_data', to='external_data.economicindicator')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economic_data', to='regions.region')),
            ],
            options={
                'verbose_name': 'Region Economic Data',
                'verbose_name_plural': 'Region Economic Data',
                'ordering': ['-year', 'region', 'indicator'],
                'constraints': [models.UniqueConstraint(fields=('region', 'indicator', 'year'), name='unique_region_indicator_year')],
            },
        ),
    ]
