# Generated by Django 6.0.5 on 2026-06-13 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('business_stage', models.CharField(choices=[('idea', 'Idea'), ('startup', 'Startup'), ('existing_business', 'Existing Business'), ('pivot', 'Pivot'), ('expansion', 'Expansion')], default='idea', max_length=32)),
                ('startup_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=16)),
                ('target_customer', models.TextField(blank=True)),
                ('business_size', models.CharField(choices=[('micro', 'Micro'), ('small', 'Small'), ('medium', 'Medium')], default='micro', max_length=16)),
                ('has_physical_location', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_snapshots', to='industries.industry')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_snapshots', to='regions.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
