# Generated by Django 5.2.15 on 2026-06-11 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_risk_level', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryRiskWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('market_weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('legal_weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('cultural_weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('operational_weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('industry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_weight', to='industries.industry')),
            ],
        ),
    ]
