# Generated by Django 5.2.15 on 2026-06-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_risk_score', models.IntegerField()),
                ('confidence_score', models.IntegerField()),
                ('confidence_label', models.CharField(max_length=50)),
                ('financial_risk', models.IntegerField()),
                ('market_risk', models.IntegerField()),
                ('legal_risk', models.IntegerField()),
                ('cultural_risk', models.IntegerField()),
                ('operational_risk', models.IntegerField()),
                ('summary', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('data_sources_used', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_reports', to='snapshots.businesssnapshot')),
            ],
            options={
                'verbose_name': 'Risk Report',
                'verbose_name_plural': 'Risk Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('market', 'Market'), ('legal', 'Legal'), ('cultural', 'Cultural'), ('operational', 'Operational')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('external_api', 'External API'), ('ai_interview', 'AI Interview'), ('user_input', 'User Input'), ('system_default', 'System Default')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='risks.riskreport')),
            ],
            options={
                'verbose_name': 'Risk Factor',
                'verbose_name_plural': 'Risk Factors',
                'ordering': ['category', 'name'],
            },
        ),
    ]
