# Generated by Django 5.2.15 on 2026-06-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=128)),
                ('country_code', models.CharField(max_length=8)),
                ('region_name', models.CharField(max_length=128)),
                ('city_name', models.CharField(blank=True, max_length=128)),
                ('region_type', models.CharField(choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural'), ('remote', 'Remote')], max_length=20)),
                ('data_availability_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('very_low', 'Very Low')], max_length=20)),
                ('is_supported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country_name', 'region_name'],
                'constraints': [models.UniqueConstraint(fields=('country_code', 'region_name'), name='unique_region_by_country')],
            },
        ),
    ]
